spring:
  application:
    name: chat
  profiles:
    active: local
  ai:
    openai:
      api-key: "your key"
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/"
      chat:
        options:
          model: "qwen-turbo"
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
  webflux:
    base-path: /chat
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://xxxx:3306/xxx
      username: xx
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
