spring:
  application:
    name: chat
  profiles:
    active: local
  ai:
    openai:
      api-key: "your key"
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/"
      chat:
        options:
          model: "qwen-turbo"
    chat:
      client:
        enabled: false
  webflux:
    base-path: /chat

server:
  port: 8080


